# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "archlinux/archlinux"

  ############################################################
  # VirtualBox Hypervisor Configuration
  ############################################################

  # Configure VM resources
  config.vm.provider "virtualbox" do |vb|
    # vb.memory =  "11240" # 11 GB RAM
    # vb.cpus = 2          # 2 CPUs
    vb.name = "ollamavm"

  end

  # Port forwarding
  ## Forwarding ollama port from guest to host using ssh
  ## vagrant ssh -- -R 11434:localhost:11434

  ############################################################
  # Mount repositories from the host
  ############################################################

  # Mount ~/usr/docs from host to /home/vagrant/docs/ in VM
  if File.directory?(File.expand_path("#{ENV['HOME']}/usr/docs"))
    config.vm.synced_folder "#{ENV['HOME']}/usr/docs", "/home/vagrant/docs/"
  end

  ############################################################
  # Provisioning
  ############################################################

  # Run the provisioning script on the first run
  config.vm.provision "shell", path: "vm_provisioner.sh"

  # Run the provisioning script as vagrant user
  config.vm.provision "shell", path: "vm_provisioner_user.sh", privileged: false

end
